# Generated by Django 5.0.6 on 2024-06-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_blog", "0002_alter_article_options_alter_article_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-pub_date"],
                "verbose_name": "Статя",
                "verbose_name_plural": "Статті",
            },
        ),
        migrations.AlterField(
            model_name="article",
            name="main_page",
            field=models.BooleanField(
                default=True,
                help_text="Показувати на головній сторінці",
                verbose_name="Головна",
            ),
        ),
    ]
